name: labwork
version: 1.0.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5

executables:
  labwork:
    main: Main.hs
    source-dirs: src
