name: C++ checker
on:
  push: {}
  pull_request: {}

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Clang-Tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy

      - name: Configure Project
        run: |
          for dir in */; do
            if [ -f "$dir/CMakeLists.txt" ]; then
              (cd "$dir" && mkdir build && cd build && cmake .. && cmake --build .)
            fi
          done
      
      - name: Run Clang-Tidy
        run: |
          for dir in */; do
            if [ -f "$dir/CMakeLists.txt" ]; then
              (cd "$dir/build" && clang-tidy -p . $(find ../prob3 -name '*.cpp') \
                $(find ../prob3 -name '*.hpp') \
                $(find ../prob28 -name '*.cpp') \
                $(find ../prob28 -name '*.hpp') \
                -- -I ../prob3/include -I ../prob28/include)
            fi
          done

  test-cpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Build CMake projects
        run: |
          for dir in */; do
            if [ -f "$dir/CMakeLists.txt" ]; then
              (cd "$dir" && mkdir build && cd build && cmake .. && cmake --build .)
            fi
          done

      - name: Run tests
        run: |
          for dir in */; do
            if [ -f "$dir/CMakeLists.txt" ]; then
              (cd "$dir/build/tests" && ctest -C 'Debug')
            fi
          done
      
